### ISSUE TITLE
FEATURE: Add a command to update the UI tests

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/command-bot#100]
Something like `bot fix ui`, which will run the command here https://github.com/paritytech/substrate/blob/master/.maintain/update-rust-stable.sh

This should help prevent any stalled PRs where UI tests are failing.

This is not a really common issue, so not high priority, but hopefully it is as easy as I think it would be.

**Comment by mordamax** [comment]
@shawntabrizi is this only for substrate?
what would be for polkadot?

**Comment by altaua** [comment]
Implemented as `bot update-ui` in https://github.com/paritytech/command-bot-scripts/pull/37
