### ISSUE TITLE
command-bot jobs get auto-canceled sporadically

### ISSUE THREAD

**Issue by coderobe** [paritytech/command-bot#103]
Sometimes gitlab's job optimization automatically culls command-bot tasks wrongly.
<img width="210" alt="image" src="https://user-images.githubusercontent.com/8442384/189088079-137ef123-7805-4131-a729-6d6712da00ea.png">

**Comment by coderobe** [comment]
https://github.com/paritytech/polkadot/pull/5980 has had a couple instances of this

**Comment by mordamax** [comment]
Should be fixed with the next release
