### ISSUE TITLE
How to run benches for all runtimes?

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/command-bot#116]
E.g. https://github.com/paritytech/polkadot/pull/6155#issuecomment-1278639790

Instead of specifying "westend", is it possible to run benchmarks for all runtimes with one command?

**Comment by ggwpez** [comment]
Currently the only way to do it is to post multiple lines:  
```pre
/cmd queue -c bench-bot $ pallet westend-dev runtime_parachains::hrmp
/cmd queue -c bench-bot $ pallet kusama-dev runtime_parachains::hrmp
```
This is far from ideal, since it compiles twice and therefore blocks the runner and queue for much longer.  
I think @mordamax is working on some improved github-external UI.

**Comment by mordamax** [comment]
I guess this is similar https://github.com/paritytech/pipeline-scripts/issues/68 ?
 but indeed, we'll try to include this case into requirements to improvements

**Comment by mordamax** [comment]
Will be improved within https://github.com/paritytech/command-bot/issues/131
