### ISSUE TITLE
Bench Bot for Release Weights

### ISSUE THREAD

**Issue by coderobe** [paritytech/command-bot#131]
@mordamax and I figure it makes sense to make the bench bot also run the release weight benchmarks, which are currently still ran manually by RelEng on bm4, 5, & 6 (not BM3).

The way it works now is that it runs benches for all pallets in per-runtime batches, so we have 4 jobs right now (rococo, westend, kusama, polkadot), and then we're manually applying the changes to our release branch. Having only 3 machines to run in parallel, we can't run them all at once - so i think it would make sense to
- add a 4th bm machine for this
- allow us to queue these jobs using the bench bot
- commit the results back to the pr/branch where it was triggered

This is essentially very similar to what it does right now when ran for individual pallets in a PR.

**Comment by coderobe** [comment]
it's also important to not use bm3 for this as to not block the bench bot for other devs during this time, which has been a complaint in the past.

**Comment by mordamax** [comment]
as I learnt from @alvicsam, ci-cd team won't add 4th BM for release automation due to https://github.com/paritytech/ci_cd/issues/583
so we need to migrate first, and then we get a new tag for this, and only then we can implement it in command bot
