### ISSUE TITLE
"Test sync chain" bot feature

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#177]
Moved from https://github.com/paritytech/opstooling/issues/95
It would be nice if the bot supports synching a certain chain, for example Kusama or later Polkadot. This should work from the Substrate/Polkadot repo. The goal is to test if `sync` is not broken. Since it could take a while (could be multiple days) it can't be part of CI but makes sense to run it occasionally from PR

Workflow for Substrate:
1. Checkout Polkadot, change the `polkadot-master` branch to the pr branch in Substrate.
2. Build Polkadot
3. Sync the requested chain.
4. Wait to sync to the tip or maybe later to a certain fixed point.

Workflow for Polkadot:
1. Build Polkadot.
2. Sync the requested chain.
3. Wait to sync to the tip or maybe later to a certain fixed point.

Request the bot:
```
// --chain=westend --sync=warp default values
bot sync 
```

```
bot sync --chain=rococo
```

```
bot sync --type=full
```

The bot comments when the task is finished.

**Comment by mordamax** [comment]
@bkchr makes sense to implement this in scope of monorepo?

**Comment by bkchr** [comment]
Yes!

**Comment by bkchr** [comment]
`polkadot --chain CHAIN`

That's it.

**Comment by mordamax** [comment]
CI / CD team had to create a separate runner for this, but it will be spawned only when sync is used.
In #245 i've added support to increase a pipeline timeout for a specific command, so it doesn't fail after 24 hours, as the majority of pipelines would do
This one is running already more than 25 hours https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3993234
Will merge this command once it's finished

**Comment by mordamax** [comment]
@bkchr is there a way to turn off the logs during sync? or reduce them

The timeout of the job is 5 days, but after 3 days, it failed due to an unknown reason, and I can't see why because `Job's log exceeded the limit of 8388608 bytes.` so it continued to run, but no way to see why failed
![image](https://github.com/paritytech/command-bot/assets/1177472/5efbade7-a8f8-4118-9f94-0779347ca1a6)

Logs: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3993234

I asked CI team to increase the limit 8 -> 16MB, but still would be great to reduce amount of logs if possible

Generally i think it's ok to merge command anyways

**Comment by bkchr** [comment]
@mordamax can you not just write the logs to a file?

**Comment by bkchr** [comment]
And warping will clearly not take 3 days, more like ~20 min (depending on the size of the state to download).

**Comment by mordamax** [comment]
@bkchr but if it fails, how do you know why?

**Comment by mordamax** [comment]
> And warping will clearly not take 3 days, more like ~20 min (depending on the size of the state to download).

could you please check this pr https://github.com/paritytech/command-bot-scripts/pull/53 ?

**Comment by bkchr** [comment]
> @bkchr but if it fails, how do you know why?

It could be an artifact of the job to download?

**Comment by bkchr** [comment]
> could you please check this pr [paritytech/command-bot-scripts#53](https://github.com/paritytech/command-bot-scripts/pull/53) ?

The node will just continue to sync on the tip of the chain if you don't stop it ;) You could for example call [`system_health`](https://github.com/paritytech/polkadot-sdk/blob/3e980219862d58aa52fd0b4dfff907d69ce92790/substrate/client/rpc-api/src/system/mod.rs#L59-L60) and check if ``is_syncing` == false`.

**Comment by mordamax** [comment]
@bkchr thanks for hint, added this check and seems like it works better :D 
https://github.com/paritytech/command-bot-scripts/pull/56
<img width="1149" alt="image" src="https://github.com/paritytech/command-bot/assets/1177472/1262c11e-eb13-48ba-843b-c6314d7fc607">

**Comment by mordamax** [comment]
Closed with https://github.com/paritytech/command-bot-scripts/pull/56
