### ISSUE TITLE
MatrixClientLite Backing off for 7926.83306175312ms

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#183]
```
2023-04-06 16:52:17 | <hr><center>nginx</center> |  
-- | -- | --
  |   | 2023-04-06 16:52:17 | <center><h1>502 Bad Gateway</h1></center> |  
  |   | 2023-04-06 16:52:17 | <body bgcolor="white"> |  
  |   | 2023-04-06 16:52:17 | <head><title>502 Bad Gateway</title></head> |  
  |   | 2023-04-06 16:52:17 | MatrixHttpClient (REQ-11686) <html> |  
  |   | 2023-04-06 16:52:17 | MatrixClientLite Backing off for 7926.83306175312ms |  
  |   | 2023-04-06 16:52:02 |   |  
  |   | 2023-04-06 16:52:02 | </html> |  
  |   | 2023-04-06 16:52:02 | </body>


```

**Comment by mutantcornholio** [comment]
But, what's the problem here? Matrix client didn't reconnect after receiving 502 from server?

**Comment by mordamax** [comment]
@mutantcornholio i guess it's pointing to the old matrix still, so we have 2 options - kill this redundant feature now or change the change it to a new matrix.
I'd prefer claening up

    MATRIX_ACCESS_TOKEN: ref+vault://kv/cicd/gitlab/parity/mirrors/command-bot/parity-prod#MATRIX_ACCESS_TOKEN
    MATRIX_HOMESERVER: ref+vault://kv/cicd/gitlab/parity/mirrors/command-bot/parity-prod#MATRIX_HOMESERVER
