### ISSUE TITLE
Bot unexpectedly triggered

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/command-bot#223]
<img width="943" alt="image" src="https://github.com/paritytech/command-bot/assets/1860335/d76381d2-f03a-41f3-8588-fc2d5e02134d">

Here: https://github.com/paritytech/substrate/pull/14260

**Comment by ggwpez** [comment]
Bot does not even like the other parity bot anymore:  

![image](https://github.com/paritytech/command-bot/assets/10380170/69f0e8af-efe0-413f-bbba-3aae90bca789)
(from https://github.com/paritytech/cumulus/pull/2657)

**Comment by mordamax** [comment]
thanks for reporting)) that's hilarious and sad at the same time) will be fixed asap)

**Comment by mordamax** [comment]
@shawntabrizi deployed a fix, it seems like it works ok now. Thanks for reporting
