### ISSUE TITLE
Deprecate processbot: re-implement `rebase` and `merge` in cmd-bot

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#228]
since we're going to stop using processbot after migration to polkadot-sdk, the cmd-bot should natively support these functions

**Comment by bkontur** [comment]
in all repos (substrate, polkadot, cumulus) I was using `bot rebase` / `bot merge`, so I just wanted to have the same possibility in our Bridges repo :)

we can use already "auto-merge + sqash and merge", so no need for `bot merge`,
`bot rebase` is kind of nice, you can rebase branches without need to checkout locally (I dont know if this is possible in github UI).

but no need to do any custom stuff for bridges repo,
lets wait for polkadot-sdk/monorepo and then come back,

I mean, it would be nice to have for Bridges repo exactly the same "cmd bot" support as pokladot-sdk repo, nothing more :)

**Comment by mutantcornholio** [comment]
> `bot rebase` is kind of nice, you can rebase branches without need to checkout locally (I dont know if this is possible in github UI).

see the screenshot above :)

**Comment by mordamax** [comment]
@bkontur our plan was to completely close the `processbot`, so `merge` and `rebase` functions are dropped too. However we could re-implement rebase, but the problem is that GitHub already supports rebase even better including for forks, while the bot can not push into forks due to lack of permission. So using GH native UI is always preferred
So I'm thinking to just closing this issue

To enable this natively - go to repo settings and turn on 2 features
 
![image](https://github.com/paritytech/command-bot/assets/1177472/0ebc22bc-99d1-41f0-8ce7-e72b3e1abdc9)

**Comment by bkontur** [comment]
@mutantcornholio  :D ok, sorry, I see "Update branch" now :D 

@mordamax ok, cool, so lets just close this
