### ISSUE TITLE
SP native runtimes soon to be removed from polkadot-sdk

### ISSUE THREAD

**Issue by seadanda** [paritytech/command-bot#242]
Bench bot runs benchmarks for system parachain runtimes which will soon be removed from the repo in [this PR](https://github.com/paritytech/polkadot-sdk/pull/1737).

When the PR is merged the following system parachain runtimes will be removed:
- `asset-hub-kusama` and `asset-hub-polkadot`
- `bridge-hub-kusama` and `bridge-hub-polkadot`
- `collectives-polkadot`
- `glutton-kusama`

New testing system parachain runtimes will be added:
- `collectives-westend`
- `glutton-westend`

The Kusama and Polkadot relay chain runtimes have already been removed from the repo.

I've made the necessary changes to `fetchCommandsConfiguration.ts` in this repo and the corresponding scripts in `command-bot-scripts` repo, but for the parsing and guessing I think it's something that I shouldn't decide: i.e. should the bot no longer even attempt to run commands for these runtimes, or should it reply with a reminder that the runtimes in question now live in the [`polkadot-fellows/runtimes` repo](https://github.com/polkadot-fellows/runtimes)?

**Comment by mordamax** [comment]
@seadanda looks like i can close this, thank you for contribution!
