### ISSUE TITLE
try-runtime CLI might have exited prematurely

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/command-bot#42]
In https://github.com/paritytech/polkadot/pull/4772#issuecomment-1031443213 the try-runtime CLI might have exited prematurely for some reason.

The process exited normally (exit code 0) according to what I observed in the logs (time 2022-02-07T13:00:57.220898488Z, ts 2022-02-07T13:00:57.341Z, tsNs 1644238857341432060 on Grafana). However, from @kianenigma on Matrix:

> https://github.com/paritytech/polkadot/pull/4772#issuecomment-1031443213
> seem to have worked until somewhere at least
> but either died, or the logs are truncated too much
> if you compare the comment from the bot with what shawntabrizi posted next, the bot seem to have died midway while scraping stuff. This is not about RUST_LOG.

**Comment by coderobe** [comment]
This is still an issue. See https://github.com/paritytech/polkadot/pull/5322#issuecomment-1098145377

**Comment by joao-paulo-parity** [comment]
> This is still an issue. See [paritytech/polkadot#5322 (comment)](https://github.com/paritytech/polkadot/pull/5322#issuecomment-1098145377)

@coderobe what is the full output?

**Comment by coderobe** [comment]
The expected output should end in something like `TryRuntime_on_runtime_upgrade executed without errors`. The log in the linked issue comment is heavily truncated (or killed) way before any of this happened, making it essentially useless.

**Comment by kianenigma** [comment]
I recall that in the past part of the issues related to try-runtime where that the instances running it would run out of resources. If that's still the case, I strongly think we are creating a self-inflicted problem. We should allocated more dedicated machines to this with enough resources.

**Comment by joao-paulo-parity** [comment]
I couldn't come back to this so far due to lack of time, but from what I suspect the issue doesn't have to do with host resources, it's something else. I expect to come back to this tomorrow or early on Monday.

**Comment by joao-paulo-parity** [comment]
> I couldn't come back to this so far due to lack of time, but from what I suspect the issue doesn't have to do with host resources

Ok I take it back, it seems like the process is being killed by the host... This wasn't being caught

I'll request more resources for that host from DevOps

**Comment by joao-paulo-parity** [comment]
Opened https://github.com/paritytech/devops/issues/1589. This issue can be closed once that's done.

**Comment by joao-paulo-parity** [comment]
Closed https://github.com/paritytech/devops/issues/1589 as per https://github.com/paritytech/devops/issues/1589#issuecomment-1120393781 but the problem hasn't been dealt with yet. It should be taken care of by https://github.com/paritytech/try-runtime-bot/pull/57.

**Comment by joao-paulo-parity** [comment]
Fixed by https://github.com/paritytech/command-bot/pull/57
