### ISSUE TITLE
Incident report: the bot became unresponsive

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/command-bot#54]
From https://github.com/paritytech/polkadot/pull/5353#issuecomment-1103994001

https://grafana.parity-mgmt.parity.io/d/ab4f13a9892a76a4d21ce8c2445bf4ea/kubernetes-pods?orgId=1&var-datasource=cortex.parity-chains&var-cluster=&var-namespace=try-runtime&var-pod=try-runtime-9fd78d96f-zf6vb&var-container=All&from=now-12h&to=now

**Comment by dvdplm** [comment]
Can you please DM me when this is fixed? Ty! 🙏

**Comment by joao-paulo-parity** [comment]
I don't expect it to be stuck anymore after https://github.com/paritytech/command-bot/pull/57. Tested recently in https://github.com/paritytech/polkadot/pull/5478#issuecomment-1124871499 and it went well.

Closing.
