### ISSUE TITLE
Use opstooling-js and opstooling-js-style

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/command-bot#58]
After https://github.com/paritytech/try-runtime-bot/pull/57 is merged, modules such as https://github.com/paritytech/try-runtime-bot/blob/master/src/logger.ts can be replaced by the ones in https://github.com/joao-paulo-parity/opstooling-js.

- [ ] opstooling-js
- [x] opstooling-js-styles
- [ ] opstooling-integrations

**Comment by mordamax** [comment]
Done
