### ISSUE TITLE
feature request: generate reference constants for the performance check

### ISSUE THREAD

**Issue by slumber** [paritytech/command-bot#59]
https://github.com/paritytech/polkadot/pull/4342 introduces new polkadot-cli command which basically checks if the machine can compile kusama runtime fast enough. For this we need some kind of time limits obtained from the reference machine.
This PR also includes a crate for generating these limits in a file. Is it feasible to extend the bot to do something like:
```sh
# checkout the given branch
cd node/test/performance-test
cargo run --release --bin gen-ref-constants
# once it finishes, node/test/performance-test/src/constants.rs is generated
cargo +nightly fmt
# commit new file and push it
```

I'm not sure since there's
>This is a substrate-only bot at the moment.

in the README.

**Comment by joao-paulo-parity** [comment]
So I take it is a new command. If that's right, it could be included in the [commandConfigurations](https://github.com/paritytech/command-bot/blob/4c7c6413fe2c1f0a47db6f96eac65d6fccd91d71/src/core.ts#L19).

**Comment by mordamax** [comment]
@slumber since kusama/polkadot runtimes are not part of polkadot-sdk, will that be needed for westend & rococo?
how often would people need to run this within PR ?

**Comment by slumber** [comment]
> @slumber 1) since kusama/polkadot runtimes are not part of polkadot-sdk, will that be needed for westend & rococo? 2) how often would people need to run this within PR ?

This command was removed from polkadot cli, hence the issue is no longer relevant
