### ISSUE TITLE
Complete the renaming

### ISSUE THREAD

**Issue by TriplEight** [paritytech/command-bot#74]
- [ ] `IMAGE_REPOSITORY: docker.io/paritytech/try-runtime-bot` https://github.com/paritytech/command-bot/blob/master/.gitlab-ci.yml#L3
- [ ] `KUBE_NAMESPACE: try-runtime` https://github.com/paritytech/command-bot/blob/master/.gitlab-ci.yml#L5
- [ ] Update logs links in https://gitlab.parity.io/groups/parity/opstooling/-/wikis/Home
- [ ] app's name  
![image](https://user-images.githubusercontent.com/17856421/171640549-41a6d164-7fbd-47ab-bf7d-62965f32178f.png)
- [ ] and since it takes to redeploy the add, please add the description to it
![image](https://user-images.githubusercontent.com/17856421/171641230-923db965-135c-4ddd-ad28-a5ecb740a042.png)

**Comment by mordamax** [comment]
Done by @alvicsam
