### ISSUE TITLE
Retry requests if the GitLab instance becomes unreachable

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/command-bot#92]
As showcased in https://github.com/paritytech/substrate/pull/11581#issuecomment-1195871737

`FetchError: request to https://gitlab.parity.io/api/v4/projects/145/pipelines/204758 failed, reason: connect ECONNREFUSED 34.159.161.55:443`

**Comment by mordamax** [comment]
Won't continue supporting GL
