### ISSUE TITLE
Bot behaviour changed or broke

### ISSUE THREAD

**Issue by coderobe** [paritytech/command-bot#94]
In https://github.com/paritytech/polkadot/pull/5759, calling try-runtime using this worked fine - now, two weeks later in https://github.com/paritytech/polkadot/pull/5827 calling the same command does not work anymore.

Either behaviour changed, or something broke - any advice?

**Comment by joao-paulo-parity** [comment]
Sorry, it broke unintendedly. Fixed by https://github.com/paritytech/pipeline-scripts/commit/892d12e234a62bab6a5c3338ddb1361cbda93a06.
