### ISSUE TITLE
Provide /cmd help with list of possible commands and aliases

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#97]
* implement the way to define aliases for long commands
> As I see from comments: most common expectation of simplicity is `bot {command}`. but this pattern is used in processbot, so we can't re-use here it probably
* send either link to help with list of commands & aliases or comment in PR 
> One of the options is - each pull-request (where bot is supported), the first comment would be listing all possible commands, or linking to docs with up-to-date list of supported bots and their commands (like tip bot, processbot, command bot, etc)

**Comment by shawntabrizi** [comment]
Ideally, there would be a list of "shortcut" commands which would map to the appropriate `/cmd` thing.

For example, benchmarking is quite a popular command, i would want a shortcut `/benchmark` which would be a string replace for `/cmd queue -v RUST_LOG=debug -c bench-bot $`.

All aliases could be listed in some JSON or similar.
